### ISSUE TITLE
`TypeError: 'NoneType' object is not iterable` (in `_remove_front_matter`)

### ISSUE THREAD

**Issue by zoni** [mfarragher/obsidiantools#1]
Running the following on my vault:

```python
import obsidiantools.api as ot
vault = ot.Vault(Path("/path/to/a/vault").connect()
```

Results in:

```
# --->8--- Irrelevant frames omitted --->8---

~/.cache/pypoetry/virtualenvs/knowledgebase-scripts-Fe_uWe_V-py3.9/lib/python3.9/site-packages/obsidiantools/md_utils.py in _get_ascii_plaintext_from_md_file(filepath)
    190     html = _get_html_from_md_file(filepath)
    191     # strip out front matter (if any):
--> 192     html = _remove_front_matter(html)
    193     return _get_ascii_plaintext_from_html(html)
    194 

~/.cache/pypoetry/virtualenvs/knowledgebase-scripts-Fe_uWe_V-py3.9/lib/python3.9/site-packages/obsidiantools/md_utils.py in _remove_front_matter(html)
    201     if hr_content:
    202         # wipe out content from first hr (the front matter)
--> 203         for fm_detail in hr_content.find_next("p"):
    204             fm_detail.extract()
    205         # then wipe all hr elements

TypeError: 'NoneType' object is not iterable
```

A quick roundtrip in a debugger shows this happens with at least:

1. Notes containing an hr (`---`) but no YAML frontmatter.
2. Notes containing only frontmatter, no body.

**Comment by mfarragher** [comment]
Thanks for raising this!  The big assumption is that the first hr carries front matter, so a fair amount of extra logic would be needed to make it robust.  Well for each of those two cases the code would need more complexity to 'recognise' front matter.

I am studying so I might not have time in coming weeks for any development.  If you have ideas feel free to submit PR for dev branch.  :smiley:   I will have a play around with a test case and see if that gives any ideas.

**Comment by mfarragher** [comment]
:one: I have tried a few horizontal rule formats (---, ***) on a basic note like this:

```md
# Horizontal rule

This note has a horizontal rule.

***

However this note has no front matter!
```

The front matter functions and attributes aren't failing (e.g. TypeError) for me, but they do cut out the note info after the rule so that is another area for making it more robust.

`_get_ascii_plaintext_from_md_file(VAULT_DIR / 'lipsum/Horizontal rule.md')` would give:

`'# Horizontal rule\n\nThis note has a horizontal rule.\n'`

Potential for this may be to parse front matter only if first line is a horizontal rule (as an if-else).

**Comment by mfarragher** [comment]
:two: I have done a note with only this content, but am not getting an error on the functions or attributes:

```md
---
title: Causam mihi
author: Ovid
category: literature
year: 8
language: la
---

```

Front matter is returning as expected:
```
{'title': 'Causam mihi',
 'author': 'Ovid',
 'category': 'literature',
 'year': 8,
 'language': 'la'}
```

and the parsed text is `\n`.

Please give a few lightweight test cases to help explore.

**Comment by mfarragher** [comment]
This is a quick fix idea that gives nicer results for my :one: and :two: test cases, I wonder if this gives improvement?

```python
def _remove_front_matter(html):
    soup = BeautifulSoup(html, 'lxml')
    initial_soup_str = str(soup)
    hr_content = soup.hr

    if hr_content and initial_soup_str.startswith('<html><body><hr/>'):
        # wipe out content from first hr (the front matter)
        for fm_detail in hr_content.find_next('p'):
            fm_detail.extract()
        # then wipe all hr elements
        for fm in soup.find_all('hr'):
            fm.decompose()
        return str(soup)
    else:
        return html
```

Outputs are:
:one:
```
'<h1>Horizontal rule</h1>\n<p>This note has a horizontal rule.</p>\n<hr>\n<p>However this note has no front matter!</p>'
```

:two: (some artefacts get introduced which is not ideal)
```
'<html><body>\n<p></p>\n</body></html>'
```

**Comment by taivop** [comment]
I think the easiest solution is to remove the frontmatter in the md file, not in HTML. That's because the frontmatter is always at the start of the file, and always is delimited by two `---` lines.

https://help.obsidian.md/Advanced+topics/YAML+front+matter

**Comment by taivop** [comment]
See my proposed implementation in https://github.com/taivop/obsidiantools/commit/027676659bcd064fe6377cdd5c7a9403e72cf2b4

I didn't add a test because adding a file into `vault-stub` breaks other tests.

**Comment by mfarragher** [comment]
Yes, doing things earlier in process (markdown rather than HTML) seems better in this scenario.

@taivop I won't be able to look at this for a few weeks but thanks for your suggestion.  If you have any small snippets that could count as small md files for test cases feel free to add in this thread. 🙂  I can update the existing tests at later stage.
@zoni do you have any unit test suggestions for your original issue, I couldn't get that TypeError?

**Comment by zoni** [comment]
@mfarragher running pytest reports a bunch of failing tests for me, even after installing all dependencies from `requirements*.txt`. See https://gist.github.com/zoni/0c271adec78d05c349518dc2d4329b96

That being said, I managed to create a reproduction case for you, see #5.

If you want some more curated test data, https://github.com/zoni/obsidian-export/tree/main/tests/testdata/input has some as well. All of those pass with the current implementation though.

**Comment by mfarragher** [comment]
Thanks :+1:

On that pytest trace, I think the first few for 'mocker' not found are from `pytest-mock` not being in requirements_test.txt.  The other ones I'm not sure what is going on there, on why the index sequence is different.  The test dataframes are based on dicts for their data, which are ordered since Python 3.6.
I am on Fedora so maybe how the filesystem is ordered is different to other OS, in how the glob does the sequence.

**Comment by mfarragher** [comment]
Have updated the dev branch with commits to fix this issue:
- Code: https://github.com/mfarragher/obsidiantools/commit/f62841c30cdfbdb163a4fb7791f952793a32d822
- Test applied to 4 test cases currently: https://github.com/mfarragher/obsidiantools/commit/64aee406f98833293d3d5ebec577748f96e5378c

The NoneType error part should be solved now, from the code block that checks for `next_content`.

The additional code that checks for headers is to deal with some test cases having header tags returned in their HTML output: e.g. frontmatter-only_1 test case returns HTML of `<hr>\n<h2>foo: bar</h2>`.
